color0       #3B3C3E
color8       #A6A256
color1       #BA69CB
color9       #BA69CB
color2       #A1A414
color10      #A1A414
color3       #07B758
color11      #07B758
color4       #F583B3
color12      #F583B3
color5       #BCBD9E
color13      #BCBD9E
color6       #EDE007
color14      #EDE007
color7       #EEE77A
color15      #EEE77A